DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS file_groups;


CREATE TABLE files(id INTEGER PRIMARY KEY AUTOINCREMENT, creator TEXT, filename TEXT);
CREATE TABLE file_groups(id INTEGER, groupname TEXT, FOREIGN KEY (id) REFERENCES files(id) ON DELETE CASCADE);
